# gitlab.ci
# File used to execute CI
# Author(s): 190014935

image: docker:20-dind

#Pipeline stages
stages:
    - build
    - test


before_script:
    - docker --version

#Build stage
build:
    stage: build
    script:
        # Database build
        - docker build -t ci-mariadb db
        - docker build -t ci-frontend frontend
        - docker build -t ci-backend backend
        - docker volume create my-db

        # Run build methods
    artifacts:                          #Artifacts for testing
        paths:
            - build/                    #(Keep anything in build folder)

#Test stage
test:
    stage: test
    script:
      # Run docker images
        - docker run ci-mariadb -dp 3307:3306 -v my-db:/var/lib/mysql
        - docker run ci-backend -dp 8080:8080 go test -v .
        - docker run ci-en

...
