volumes:
  db_data:

networks:
  backend:
    driver: bridge

services:
  db:
    build: ./db
    networks:
      - backend
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    depends_on:
      - db
    links:
      - db
    networks:
      - backend
    ports:
      - "3333:3333"
    volumes:
      - ./logs:/var/tmp/cs3099-log
    environment:
      LOG_PATH: "/var/tmp/cs3099-log/cs3099-backend.log"
      DATABASE_URL: "myuser:mypass@tcp(localhost:3307)"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "23409:23409"
    environment:
      NODE_ENV: "nodocker"
