volumes:
  db_data:
  file_sys:

services:
  db:
    build: ./db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "3333:3333"
    volumes:
      - ./logs:/var/tmp/cs3099-log
      - file_sys:/filesystem
    environment:
      LOG_PATH: "/var/tmp/cs3099-log/cs3099-backend.log"
      DATABASE_URL: "myuser:mypass@tcp(db:3306)"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "23409:23409"
    environment:
      NODE_ENV: "development"
    volumes:
      - ./frontend:/usr/src/app
