package main

import (
	"database/sql"
	"fmt"
	"log"
	_ "github.com/go-sql-driver/mysql"
	"reflect"
	"time"
)

var db *sql.DB

const (
	TEAM_ID         = "11"

	// Constant for table operations.
	VIEW_PERMISSIONS = "globalPermissions"
	TABLE_SERVERS	 = "servers"
	VIEW_LOGIN		 = "globalLogins"
	TABLE_USERS     = "users"
	TABLE_PROJECTS  = "projects"
	TABLE_FILES     = "files"
	TABLE_AUTHORS   = "authors"
	TABLE_REVIEWERS = "reviewers"
	TABLE_CATEGORIES = "categories"
	TABLE_IDMAPPINGS = "idMappings"
	VIEW_USER_INFO	= "globalUserInfo"
	VIEW_PROJECTLIST = "projectList"

	// TEMP: reconcile these
	INNER_JOIN       = "%s INNER JOIN %s"
	INSERT_DOUBLE    = "INSERT INTO %s (%s, %s) VALUES (?, ?)"

	SELECT_ROW               = "SELECT %s FROM %s WHERE %s = ?"
	SELECT_EXISTS            = "SELECT EXISTS (SELECT %s FROM %s WHERE %s = ?)"
	SELECT_ROW_TWO_CONDITION = "SELECT %s FROM %s WHERE %s = ? AND %s = ?"
	SELECT_ALL_ORDER_BY      = "SELECT %s FROM %s ORDER BY ?"
	SELECT_ROW_INNER_JOIN    = "SELECT %s FROM %s INNER JOIN %s ON %s = %s WHERE %s = ?"
	SELECT_ROW_ORDER_BY      = "SELECT %s FROM %s ORDER BY ? WHERE %s = ?"
	INSERT_CRED              = "INSERT INTO %s (%s, %s, %s, %s) VALUES (?, ?, ?, ?)"
	INSERT_PROJ              = "INSERT INTO %s (%s) VALUES (?) RETURNING id"
	INSERT_FILE              = "INSERT INTO %s (%s, %s) VALUES (?, ?) RETURNING id"
	INSERT_AUTHOR            = "INSERT INTO %s VALUES (?, ?)"
	INSERT_REVIEWER          = "INSERT INTO %s VALUES (?, ?)"
	INSERT_FULL              = "INSERT INTO %s (%s, %s, %s, %s, %s, %s, %s) VALUES (?, ?, ?, ?, ?, ?, ?)"
	UPDATE_ROWS              = "UPDATE %s SET %s = ? WHERE %s = ?"
	DELETE_ALL_ROWS          = "DELETE FROM %s"

	USERTYPE_NIL                = 0
	USERTYPE_PUBLISHER          = 1
	USERTYPE_REVIEWER           = 2
	USERTYPE_REVIEWER_PUBLISHER = 3
	USERTYPE_USER               = 4
)

var DB_PARAMS map[string]string = map[string]string{
	"interpolateParams": "true",
}

// Structure for user table.
type Credentials struct {
	// User auto incremented ID.
	Id string `json:"userId" db:"id"`
	// Email Address.
	Email string `json:"email" db:"email" validate:"nonzero,max=100"`
	// Password - given as plaintext by front end, and as hash by the database.
	Pw string `json:"password,omitempty" db:"password" validate:"min=8,max=64,validpw"`
	// First Name.
	Fname string `json:"firstname" db:"firstName" validate:"nonzero,max=32"`
	// Last Name.
	Lname string `json:"lastname" db:"lastName" validate:"nonzero,max=32"`
	// User role.
	Usertype int `json:"usertype" db:"userType"`
	// User phone number.
	PhoneNumber string `json:"phonenumber" db:"phoneNumber" validate:"max=11"`
	// Organization name.
	Organization string `json:"organization" db:"organization" validate:"max=32"`
}

// Structure for ID mappings.
type IdMappings struct {
	GlobalId string `json:"globalId" db:"globalId"`
	Id       string `json:"userId" db:"localId"`
}

// Structure for code Projects
type Project struct {
	// unique id for the project as generated by the db
	Id int `json:"id" db:"id"`
	// name of the project
	Name string `json:"name" db:"projectName"` // TEMP: change to just "Name"
	// the ids of the project's reviewers
	Reviewers []string `json:"reviewers"`
	// the ids of the project's authors
	Authors []string `json:"authors"`
	// file paths associated with the project
	FilePaths []string `json:"files" db:"filePath"`

	// TEMP: add more fields (i.e. reviewer reviews)
}

// Structure for code files
type File struct {
	// unique id of the file as maintained in the db
	Id int `json:"id" db:"id"`
	// id of the project this file is a part of
	ProjectId int `json:"projectId" db:"projectId"`
	// name of the project this file is a part of
	ProjectName string `json:"projectName"`
	// relative path to the file from the root of the project
	Path string `json:"filePath" db:"filePath"`
	// base name of the file with extension
	Name string `json:"name"`
	// content of the file encoded as a Base64 string
	Content string `json:"content"`
	// user comments on the file
	Comments []*Comment `json:"comments"`
}

// Structure for user comments on code
type Comment struct {
	// author of the comment as an id
	AuthorId string `json:"author"`
	// time that the comment was recorded as a string 
	Time string `json:"time"`
	// content of the comment as a string
	Content string `json:"content"`
	// replies TEMP: maybe don't allow nested replies?
	Replies []*Comment `json:"replies"`
}

// Structure for authors and reviewers
type AuthorsReviewers struct {
	ProjectId int `json:"projectId" db:"projectId"`
	Id string `json:"id" db:"userId"`
}

// structure to hold json data from data files
type CodeFileData struct {
	// TEMP: add IsReviewed field
	Comments []*Comment `json:"comments"`
}

// structure to hold supergroup compliant project metadata
type SupergroupSubmissionMetaData struct {
	// creation date of the project
	CreationDate string `json:"creationDate"`
	// author name
	AuthorName string `json:"authorName"`
}

type SuperGroupFile struct {
	Name string `json:"filename"`
	Content string `json:"base64Value"`
}

// structure to hold formatted supergroup submissions
type SupergroupSubmission struct {
	// name of the project
	Name string `json:"name"`
	// metadata about the submission
	Metadata *SupergroupSubmissionMetaData `json:"metadata"`
	// files array
	Files []*SuperGroupFile `json:"files"`
}


// Structure for servers.
type Servers struct {
	GroupNb	int `json:"groupNumber" db:"groupNumber"`
	Token	string `json:"token" db:"token"`
	Url		string `json:"url" db:"url"`
}

// Get the tag in a struct.
func getTag(v interface{}, structVar string, tag string) string {
	field, ok := reflect.TypeOf(v).Elem().FieldByName(structVar)
	if !ok {
		return ""
	} else {
		return field.Tag.Get(tag)
	}
}

// Check if a value is unique in a given table.
func checkUnique(table string, varName string, val string) bool {
	// Query prepared and formatted statement.
	stmt := fmt.Sprintf(SELECT_ROW, varName, table, varName)
	query := db.QueryRow(stmt, val)

	// Scan query and check for existing rows.
	var res interface{}
	err := query.Scan(&res)
	if err != sql.ErrNoRows {
		// Table isn't empty or error occured, return false.
		if err != nil {
			log.Printf("Scan error on checkUnique: %v\n", err)
		}
		return false
	} else {
		return true
	}
}

// Get the database tag for a struct.
func getDbTag(v interface{}, structVar string) string {
	return getTag(v, structVar, "db")
}

// Get the database tag for a struct.
func getJsonTag(v interface{}, structVar string) string {
	return getTag(v, structVar, "json")
}

// Get database parameters string to place into DSN from a map.
func getDbParams(paramMap map[string]string) string {
	params := ""
	i := 0
	for key, val := range paramMap {
		if i > 0 {
			params += "&"
		}
		params += key + "=" + val
		i++
	}
	return params
}

// Initialise connection to the database.
func dbInit(user string, pw string, protocol string, h string, port int, dbname string) error {
	var err error

	// Set MySQL info in DSN format according to Go MySQL Drive -
	// user:password@protocol(host:port)/dbname?[param1=val...]
	mysqlInfo := fmt.Sprintf("%s:%s@%s(%s:%d)/%s?%s", user, pw, protocol, h, port, dbname,
		getDbParams(DB_PARAMS)) // Setting this to allow prepared statements.
	db, err = sql.Open("mysql", mysqlInfo)
	if err != nil {
		return err
	}

	// Set connection sanity options for database.
	db.SetConnMaxLifetime(time.Minute * 3)
	db.SetMaxOpenConns(10)
	db.SetMaxIdleConns(10)
	return nil
}

// Close a database connection.
// WARNING: this function clears all data from the database, setting it
// back to the state it'd be in 
func dbClear() error {
	// db tables to clear ORDER MATTERS HERE
	tablesToClear := []string{
		TABLE_CATEGORIES,
		TABLE_AUTHORS,
		TABLE_REVIEWERS,
		TABLE_FILES,
		TABLE_PROJECTS,
		TABLE_IDMAPPINGS,
		TABLE_USERS,
	}
	// formats and executes a delete command for each table
	for _, table := range tablesToClear {
		stmt := fmt.Sprintf(DELETE_ALL_ROWS, table)
		_, err := db.Exec(stmt)
		if err != nil {
			return err
		}
	}
	return nil
}

// Close database connection.
func dbCloseConnection() {
	db.Close()
}

// Get all columns from an interface.
func getCols(v interface{}) []interface{} {
	s := reflect.ValueOf(v).Elem()
	numCols := s.NumField()
	cols := make([]interface{}, numCols)
	for i := 0; i < numCols; i++ {
		cols[i] = s.Field(i).Addr().Interface()
	}
	return cols
}
